// Code generated by sqlc. DO NOT EDIT.
// source: complex.sql

package db

import (
	"context"
	"database/sql"
)

const createComplex = `-- name: CreateComplex :one
INSERT INTO complexes ("bitrix_id", "name")
VALUES ($1, $2)
RETURNING id, bitrix_id, name
`

type CreateComplexParams struct {
	BitrixID int64          `json:"bitrix_id"`
	Name     sql.NullString `json:"name"`
}

func (q *Queries) CreateComplex(ctx context.Context, arg CreateComplexParams) (Complex, error) {
	row := q.db.QueryRowContext(ctx, createComplex, arg.BitrixID, arg.Name)
	var i Complex
	err := row.Scan(&i.ID, &i.BitrixID, &i.Name)
	return i, err
}
