// Code generated by sqlc. DO NOT EDIT.
// source: litter.sql

package db

import (
	"context"
	"database/sql"
)

const createLitter = `-- name: CreateLitter :one
INSERT INTO litters ("parent", "bitrix_id", "name")
VALUES ($1, $2, $3)
RETURNING id, parent, bitrix_id, name
`

type CreateLitterParams struct {
	Parent   int64          `json:"parent"`
	BitrixID int64          `json:"bitrix_id"`
	Name     sql.NullString `json:"name"`
}

func (q *Queries) CreateLitter(ctx context.Context, arg CreateLitterParams) (Litter, error) {
	row := q.db.QueryRowContext(ctx, createLitter, arg.Parent, arg.BitrixID, arg.Name)
	var i Litter
	err := row.Scan(
		&i.ID,
		&i.Parent,
		&i.BitrixID,
		&i.Name,
	)
	return i, err
}
