// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type Complex struct {
	ID       int64          `json:"id"`
	BitrixID int64          `json:"bitrix_id"`
	Name     sql.NullString `json:"name"`
}

type Layout struct {
	ID          int64           `json:"id"`
	Parent      int64           `json:"parent"`
	Area        sql.NullFloat64 `json:"area"`
	CitchenArea sql.NullFloat64 `json:"citchen_area"`
	Door        sql.NullInt32   `json:"door"`
	Floor       sql.NullInt32   `json:"floor"`
	BitrixID    sql.NullInt32   `json:"bitrix_id"`
	LayoutID    sql.NullInt32   `json:"layout_id"`
	LivingArea  sql.NullFloat64 `json:"living_area"`
	Num         sql.NullString  `json:"num"`
	Price       sql.NullInt32   `json:"price"`
	Status      sql.NullInt32   `json:"status"`
	Type        sql.NullInt32   `json:"type"`
	Room        sql.NullInt32   `json:"room"`
	SvgPath     sql.NullString  `json:"svg_path"`
}

type Litter struct {
	ID       int64          `json:"id"`
	Parent   int64          `json:"parent"`
	BitrixID int64          `json:"bitrix_id"`
	Name     sql.NullString `json:"name"`
}

type StaRoom struct {
	ID       int64          `json:"id"`
	BitrixID int64          `json:"bitrix_id"`
	TypeName sql.NullString `json:"type_name"`
}

type StaStatus struct {
	ID       int64          `json:"id"`
	BitrixID int64          `json:"bitrix_id"`
	TypeName sql.NullString `json:"type_name"`
}

type StaType struct {
	ID       int64          `json:"id"`
	BitrixID int64          `json:"bitrix_id"`
	TypeName sql.NullString `json:"type_name"`
}
