// Code generated by sqlc. DO NOT EDIT.
// source: staRoom.sql

package db

import (
	"context"
	"database/sql"
)

const createStaRoom = `-- name: CreateStaRoom :one
INSERT INTO sta_room ("bitrix_id", "type_name")
VALUES ($1, $2)
RETURNING id, bitrix_id, type_name
`

type CreateStaRoomParams struct {
	BitrixID int64          `json:"bitrix_id"`
	TypeName sql.NullString `json:"type_name"`
}

func (q *Queries) CreateStaRoom(ctx context.Context, arg CreateStaRoomParams) (StaRoom, error) {
	row := q.db.QueryRowContext(ctx, createStaRoom, arg.BitrixID, arg.TypeName)
	var i StaRoom
	err := row.Scan(&i.ID, &i.BitrixID, &i.TypeName)
	return i, err
}

const getListAllStaRoom = `-- name: GetListAllStaRoom :many
SELECT id, bitrix_id, type_name
FROM sta_room
ORDER BY id
`

func (q *Queries) GetListAllStaRoom(ctx context.Context) ([]StaRoom, error) {
	rows, err := q.db.QueryContext(ctx, getListAllStaRoom)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StaRoom
	for rows.Next() {
		var i StaRoom
		if err := rows.Scan(&i.ID, &i.BitrixID, &i.TypeName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
