// Code generated by sqlc. DO NOT EDIT.
// source: staStatuse.sql

package db

import (
	"context"
	"database/sql"
)

const createStaStatuse = `-- name: CreateStaStatuse :one
INSERT INTO sta_statuses ("bitrix_id", "type_name")
VALUES ($1, $2)
RETURNING id, bitrix_id, type_name
`

type CreateStaStatuseParams struct {
	BitrixID int64          `json:"bitrix_id"`
	TypeName sql.NullString `json:"type_name"`
}

func (q *Queries) CreateStaStatuse(ctx context.Context, arg CreateStaStatuseParams) (StaStatus, error) {
	row := q.db.QueryRowContext(ctx, createStaStatuse, arg.BitrixID, arg.TypeName)
	var i StaStatus
	err := row.Scan(&i.ID, &i.BitrixID, &i.TypeName)
	return i, err
}
