// Code generated by sqlc. DO NOT EDIT.
// source: staType.sql

package db

import (
	"context"
	"database/sql"
)

const createStaType = `-- name: CreateStaType :one
INSERT INTO sta_types ("bitrix_id", "type")
VALUES ($1, $2)
RETURNING id, bitrix_id, type
`

type CreateStaTypeParams struct {
	BitrixID int64          `json:"bitrix_id"`
	Type     sql.NullString `json:"type"`
}

func (q *Queries) CreateStaType(ctx context.Context, arg CreateStaTypeParams) (StaType, error) {
	row := q.db.QueryRowContext(ctx, createStaType, arg.BitrixID, arg.Type)
	var i StaType
	err := row.Scan(&i.ID, &i.BitrixID, &i.Type)
	return i, err
}
