// Code generated by sqlc. DO NOT EDIT.
// source: staType.sql

package db

import (
	"context"
	"database/sql"
)

const createStaType = `-- name: CreateStaType :one
INSERT INTO sta_types ("bitrix_id", "type_name")
VALUES ($1, $2)
RETURNING id, bitrix_id, type_name
`

type CreateStaTypeParams struct {
	BitrixID int64          `json:"bitrix_id"`
	TypeName sql.NullString `json:"type_name"`
}

func (q *Queries) CreateStaType(ctx context.Context, arg CreateStaTypeParams) (StaType, error) {
	row := q.db.QueryRowContext(ctx, createStaType, arg.BitrixID, arg.TypeName)
	var i StaType
	err := row.Scan(&i.ID, &i.BitrixID, &i.TypeName)
	return i, err
}

const getListAllStaType = `-- name: GetListAllStaType :many
SELECT id, bitrix_id, type_name
FROM sta_types
ORDER BY id
`

func (q *Queries) GetListAllStaType(ctx context.Context) ([]StaType, error) {
	rows, err := q.db.QueryContext(ctx, getListAllStaType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StaType
	for rows.Next() {
		var i StaType
		if err := rows.Scan(&i.ID, &i.BitrixID, &i.TypeName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
